# Generated by Django 3.1.3 on 2020-11-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('site', models.CharField(max_length=128)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
